@startuml yonde
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "users" as users {
  id
  --
  name
  email
  encrypted_password
  salt
  created_at
  updated_at
}

entity "pc_entrust_sets" as pc_entrust_sets {
  id
  --
  parts_cpus_id<<FK>>
  parts_os_id<<FK>>
  parts_graphics_id<<FK>>
  parts_memorys_id<<FK>>
  parts_storages_id<<FK>>
  parts_adds_id<<FK>>
  budget
  price
  use_case
  name
  created_at
  updated_at
}

entity "pc_custom_sets" as pc_custom_sets {
  id
  --
  user_id<<FK>>
  parts_cpus_id<<FK>>
  parts_os_id<<FK>>
  parts_graphics_id<<FK>>
  parts_memorys_id<<FK>>
  parts_storages_id<<FK>>
  parts_adds_id<<FK>>
  budget
  price
  use_case
  name
  created_at
  updated_at
}

entity "parts_cpus" as parts_cpus {
  id
  --
  name
  price
  maker
  created_at
  updated_at
}

entity "parts_os" as parts_os {
  id
  --
  name
  price
  created_at
  updated_at
}

entity "parts_graphics" as parts_graphics {
  id
  --
  name
  price
  maker
  created_at
  updated_at
}

entity "parts_memorys" as parts_memorys {
  id
  --
  name
  price
  maker
  created_at
  updated_at
}

entity "parts_storages" as parts_storages {
  id
  --
  name
  price
  maker
  created_at
  updated_at
}

entity "parts_adds" as parts_adds {
  id
  --
  parts_adds_id<<FK>>
  category_name
  name
  price
  maker
  created_at
  updated_at
}

entity "pc_custum_adds" as pc_custum_adds {
  id
  --
  pc_parts_id<<FK>>
  parts_adds_id<<FK>>
  created_at
  updated_at
}

users ||--o{ pc_custom_sets
pc_custom_sets ||--o{ pc_custum_adds
parts_adds ||--o{ pc_custum_adds
parts_cpus ||--o{ pc_custom_sets
parts_os ||--o{ pc_custom_sets
parts_graphics ||--o{ pc_custom_sets
parts_memorys ||--o{ pc_custom_sets
parts_storages ||--o{ pc_custom_sets

@enduml
